version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: lokko-tubesync
      APP_PORT: 4848
  web:
    image: ghcr.io/meeb/tubesync:latest
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "4848:4848"
    volumes:
      - ${APP_DATA_DIR}:/downloads
